### ISSUE TITLE
Babylon Tech Glitch Part II

### ISSUE THREAD

**Issue by 1SDANi** [dguenms/Dawn-of-Civilization#149]
Using the latest version of hrcivics, I found that loading an autosave that takes place on the exact turn you get a tech gives you the message that "You have already chosen a free tech" after selecting a free tech instead of giving you said tech. Reloading the game does not fix it, it seems embedded into the autosave.

**Comment by dguenms** [comment]
Okay, looks like I'm still not done with that. Will investigate.

**Comment by dguenms** [comment]
Has been fixed now.
