### ISSUE TITLE
Mongol conquerors for Arabia

### ISSUE THREAD

**Issue by MeuhV1** [dguenms/Dawn-of-Civilization#19]
In RhyesAndFall.py, in line 2709, there is a selection if iTeamX is Arabia or Persia. However, it can never be Arabia, because that one is already excluded in line 2692, where iTeamX can only be Persia, Russia or Byzantium.

So Mongolia doesn't receive conquerors for Arabia. Intended?

**Comment by dguenms** [comment]
I think I deliberately removed Arabia from the list of Mongol targets. No reason to delete functional code in case I ever want to add them back in.
