### ISSUE TITLE
Modify Babylon's first UHV to make it possible to achieve?

### ISSUE THREAD

**Issue by hanfeisun** [dguenms/Dawn-of-Civilization#257]
As suggested in several threads ([1](https://forums.civfanatics.com/threads/babylon-tech-order.623057/), [2](https://forums.civfanatics.com/threads/1-15-babylon-whining.629763/)), the Babylon UHV1 in Doc 1.15 is (almost) impossible to achieve.

Probably we can replace "Be the first to discover Construction" with "Be the first to discover Laws"?

**Comment by dguenms** [comment]
That's true, I will look into that at some later point.
