### ISSUE TITLE
Can't start from RFC 600 in 1.16 RC?

### ISSUE THREAD

**Issue by hanfeisun** [dguenms/Dawn-of-Civilization#283]
When I click "Play Scenerio -> RFC 600", I saw an error message like this:

![Civ IV_ Beyond The Sword 4_29_2019 7_54_21 PM](https://user-images.githubusercontent.com/922081/56938812-2a23e400-6ab9-11e9-891e-9018a1e0c24d.png)

I used the zip package of v1.16.0-rc, not sure what the root cause of this issue is.

RFC BC 3000 and RFC AD 1700 works well for me. Only the RFC AD 600 doesn't work

**Comment by mechu1205** [comment]
Open the AD600 map file in Dawn of Civilization\PrivateMaps via Notepad++.
Edit - EOL Conversion - Convert to Windows and save.

**Comment by hanfeisun** [comment]
Thanks!
