### ISSUE TITLE
Hi, I can't seem to find the map branch

### ISSUE THREAD

**Issue by MegasKomnenos** [dguenms/Dawn-of-Civilization#346]
So I searched through the closed PRs to find a PR on the map branch, and I was able to find some, which means the map branch does or did exist. However, when I click on it, I just get a 404 error. Does anyone know why that would be the case?

**Comment by dguenms** [comment]
I assume you asked the same question in the CFC forum. I answered you there. If it was not you, please contact me on CFC regardless.
