### ISSUE TITLE
Help... cannot find maps starting game

### ISSUE THREAD

**Issue by kingdomunder** [dguenms/Dawn-of-Civilization#357]
![image](https://user-images.githubusercontent.com/85289172/205427023-0e2d0742-4ad7-4fc0-8049-e3d9bc20fe54.png)

i cloned repo from develop branch and renamed folder to 'RFC Dawn of Civilization'.
no error message anywhere but there are no maps when click play a scenario.
could you please tell me how can I fix it?

**Comment by MatthewForrester** [comment]
Welcome to _Dawn of Civilization_ :wave:

In the latest version, you need to use the "Play Now" button to begin games. Have you tried that?

Also, you can find much more information at [the Dawn of Civilization forum](https://forums.civfanatics.com/forums/rhyes-and-fall-dawn-of-civilization.452/).

**Comment by dguenms** [comment]
Thank you for answering, I think that should solve the problem.

If any issues remain, or a new problem comes up, please raise it in the forum. It is much more likely to be seen and you can get help from the entire community.

**Comment by kingdomunder** [comment]
I checked issue too late.. I haven't played the game for a while, but I'll check it out.

Thank you for advice.
