### ISSUE TITLE
Where is the DOC map mode on 1.17?

### ISSUE THREAD

**Issue by HarutoLiang** [dguenms/Dawn-of-Civilization#359]
I remember there is a DOC map mode in WorldBuilder that can check and adjust core area and flipzone on 1.16,it's pretty useful. Where has it moved on 1.17?

I am using the "Dawn of Civilization v1.17.0 with all modules" version that posted on forum.

**Comment by dguenms** [comment]
It has been removed because I no longer wanted to maintain it.

In the future, please ask questions in the forum instead of creating a github issue, thanks.
