### ISSUE TITLE
Mission requirements persist across different games.

### ISSUE THREAD

**Issue by RafalLauterbach** [dguenms/Dawn-of-Civilization#360]
I have problem - as in title. It didn't happened in 1.16. 

I'm playing Babylonia, I failed to research Arithmetic as first, so I started new run. After restart I still have writing requirement ticked as "done" already in 3000BC. When Greece spawn again beats me to Arithmetic it doesn't tell me that I lose and also - once I research Arithmetic it doesn't tick it as "done" (effectively tech mission stays "not yet" forever, it doesn't collapse into NO/YES)

Restarting entire game helps. But going to menu and making new game always reproduces problem in my enviroment.

I don't know if this bug happens for all of you (especially Windows users), but I'm playing DoC(17.0) on Linux (Ubuntu 20.04.6) + Proton (7.06) on Steam. If it might be platform (some library version) dependent, I might try different proton versions, for now I just bare with restarting whole game.

**Comment by dguenms** [comment]
I pushed a fix for this issue recently, are you up to date?

**Comment by RafalLauterbach** [comment]
I'm already using 1.17.0, I've seen only one 1.17.x version in releases and thought that's it. 
If I understand correctly, I will need to clone->download zip instead of using released version? 
I will do it tomorrow if I have time. I guess it'll work then. Thanks for fixing it : )
